// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email.proto

#include "email.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace email {

inline constexpr UserRetrieveEmail::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : useremail_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserRetrieveEmail::UserRetrieveEmail(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserRetrieveEmailDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserRetrieveEmailDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserRetrieveEmailDefaultTypeInternal() {}
  union {
    UserRetrieveEmail _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserRetrieveEmailDefaultTypeInternal _UserRetrieveEmail_default_instance_;

inline constexpr UserRegisterEmail::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : useremail_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserRegisterEmail::UserRegisterEmail(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserRegisterEmailDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserRegisterEmailDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserRegisterEmailDefaultTypeInternal() {}
  union {
    UserRegisterEmail _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserRegisterEmailDefaultTypeInternal _UserRegisterEmail_default_instance_;

inline constexpr RetrieveEmailReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sendstate_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RetrieveEmailReply::RetrieveEmailReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RetrieveEmailReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RetrieveEmailReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RetrieveEmailReplyDefaultTypeInternal() {}
  union {
    RetrieveEmailReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RetrieveEmailReplyDefaultTypeInternal _RetrieveEmailReply_default_instance_;

inline constexpr RegisterEmailReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sendstate_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RegisterEmailReply::RegisterEmailReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RegisterEmailReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterEmailReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterEmailReplyDefaultTypeInternal() {}
  union {
    RegisterEmailReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterEmailReplyDefaultTypeInternal _RegisterEmailReply_default_instance_;
}  // namespace email
static ::_pb::Metadata file_level_metadata_email_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_email_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_email_2eproto = nullptr;
const ::uint32_t TableStruct_email_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::email::UserRegisterEmail, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::email::UserRegisterEmail, _impl_.useremail_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::email::RegisterEmailReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::email::RegisterEmailReply, _impl_.sendstate_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::email::UserRetrieveEmail, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::email::UserRetrieveEmail, _impl_.useremail_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::email::RetrieveEmailReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::email::RetrieveEmailReply, _impl_.sendstate_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::email::UserRegisterEmail)},
        {9, -1, -1, sizeof(::email::RegisterEmailReply)},
        {18, -1, -1, sizeof(::email::UserRetrieveEmail)},
        {27, -1, -1, sizeof(::email::RetrieveEmailReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::email::_UserRegisterEmail_default_instance_._instance,
    &::email::_RegisterEmailReply_default_instance_._instance,
    &::email::_UserRetrieveEmail_default_instance_._instance,
    &::email::_RetrieveEmailReply_default_instance_._instance,
};
const char descriptor_table_protodef_email_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013email.proto\022\005email\"&\n\021UserRegisterEmai"
    "l\022\021\n\tuseremail\030\001 \001(\t\"\'\n\022RegisterEmailRep"
    "ly\022\021\n\tsendstate\030\001 \001(\005\"&\n\021UserRetrieveEma"
    "il\022\021\n\tuseremail\030\001 \001(\t\"\'\n\022RetrieveEmailRe"
    "ply\022\021\n\tsendstate\030\001 \001(\0052\247\001\n\005Email\022N\n\025post"
    "RegisterEmailCode\022\030.email.UserRegisterEm"
    "ail\032\031.email.RegisterEmailReply\"\000\022N\n\025post"
    "RetrieveEmailCode\022\030.email.UserRetrieveEm"
    "ail\032\031.email.RetrieveEmailReply\"\000B1\n\026io.g"
    "rpc.teamchat.emailB\nEmailProtoP\001\242\002\010TC_Em"
    "ailb\006proto3"
};
static ::absl::once_flag descriptor_table_email_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_email_2eproto = {
    false,
    false,
    411,
    descriptor_table_protodef_email_2eproto,
    "email.proto",
    &descriptor_table_email_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_email_2eproto::offsets,
    file_level_metadata_email_2eproto,
    file_level_enum_descriptors_email_2eproto,
    file_level_service_descriptors_email_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_email_2eproto_getter() {
  return &descriptor_table_email_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_email_2eproto(&descriptor_table_email_2eproto);
namespace email {
// ===================================================================

class UserRegisterEmail::_Internal {
 public:
};

UserRegisterEmail::UserRegisterEmail(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:email.UserRegisterEmail)
}
inline PROTOBUF_NDEBUG_INLINE UserRegisterEmail::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : useremail_(arena, from.useremail_),
        _cached_size_{0} {}

UserRegisterEmail::UserRegisterEmail(
    ::google::protobuf::Arena* arena,
    const UserRegisterEmail& from)
    : ::google::protobuf::Message(arena) {
  UserRegisterEmail* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:email.UserRegisterEmail)
}
inline PROTOBUF_NDEBUG_INLINE UserRegisterEmail::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : useremail_(arena),
        _cached_size_{0} {}

inline void UserRegisterEmail::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserRegisterEmail::~UserRegisterEmail() {
  // @@protoc_insertion_point(destructor:email.UserRegisterEmail)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserRegisterEmail::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.useremail_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserRegisterEmail::Clear() {
// @@protoc_insertion_point(message_clear_start:email.UserRegisterEmail)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.useremail_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserRegisterEmail::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> UserRegisterEmail::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserRegisterEmail_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string useremail = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserRegisterEmail, _impl_.useremail_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string useremail = 1;
    {PROTOBUF_FIELD_OFFSET(UserRegisterEmail, _impl_.useremail_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\11\0\0\0\0\0\0"
    "email.UserRegisterEmail"
    "useremail"
  }},
};

::uint8_t* UserRegisterEmail::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:email.UserRegisterEmail)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string useremail = 1;
  if (!this->_internal_useremail().empty()) {
    const std::string& _s = this->_internal_useremail();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "email.UserRegisterEmail.useremail");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:email.UserRegisterEmail)
  return target;
}

::size_t UserRegisterEmail::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:email.UserRegisterEmail)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string useremail = 1;
  if (!this->_internal_useremail().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_useremail());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserRegisterEmail::_class_data_ = {
    UserRegisterEmail::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserRegisterEmail::GetClassData() const {
  return &_class_data_;
}

void UserRegisterEmail::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserRegisterEmail*>(&to_msg);
  auto& from = static_cast<const UserRegisterEmail&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:email.UserRegisterEmail)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_useremail().empty()) {
    _this->_internal_set_useremail(from._internal_useremail());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserRegisterEmail::CopyFrom(const UserRegisterEmail& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:email.UserRegisterEmail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserRegisterEmail::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserRegisterEmail::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserRegisterEmail::InternalSwap(UserRegisterEmail* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.useremail_, &other->_impl_.useremail_, arena);
}

::google::protobuf::Metadata UserRegisterEmail::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_email_2eproto_getter, &descriptor_table_email_2eproto_once,
      file_level_metadata_email_2eproto[0]);
}
// ===================================================================

class RegisterEmailReply::_Internal {
 public:
};

RegisterEmailReply::RegisterEmailReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:email.RegisterEmailReply)
}
RegisterEmailReply::RegisterEmailReply(
    ::google::protobuf::Arena* arena, const RegisterEmailReply& from)
    : RegisterEmailReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RegisterEmailReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RegisterEmailReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sendstate_ = {};
}
RegisterEmailReply::~RegisterEmailReply() {
  // @@protoc_insertion_point(destructor:email.RegisterEmailReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterEmailReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RegisterEmailReply::Clear() {
// @@protoc_insertion_point(message_clear_start:email.RegisterEmailReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sendstate_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterEmailReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RegisterEmailReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterEmailReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 sendstate = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RegisterEmailReply, _impl_.sendstate_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterEmailReply, _impl_.sendstate_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sendstate = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterEmailReply, _impl_.sendstate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RegisterEmailReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:email.RegisterEmailReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 sendstate = 1;
  if (this->_internal_sendstate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_sendstate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:email.RegisterEmailReply)
  return target;
}

::size_t RegisterEmailReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:email.RegisterEmailReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 sendstate = 1;
  if (this->_internal_sendstate() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_sendstate());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterEmailReply::_class_data_ = {
    RegisterEmailReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RegisterEmailReply::GetClassData() const {
  return &_class_data_;
}

void RegisterEmailReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterEmailReply*>(&to_msg);
  auto& from = static_cast<const RegisterEmailReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:email.RegisterEmailReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sendstate() != 0) {
    _this->_internal_set_sendstate(from._internal_sendstate());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterEmailReply::CopyFrom(const RegisterEmailReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:email.RegisterEmailReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterEmailReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RegisterEmailReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RegisterEmailReply::InternalSwap(RegisterEmailReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sendstate_, other->_impl_.sendstate_);
}

::google::protobuf::Metadata RegisterEmailReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_email_2eproto_getter, &descriptor_table_email_2eproto_once,
      file_level_metadata_email_2eproto[1]);
}
// ===================================================================

class UserRetrieveEmail::_Internal {
 public:
};

UserRetrieveEmail::UserRetrieveEmail(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:email.UserRetrieveEmail)
}
inline PROTOBUF_NDEBUG_INLINE UserRetrieveEmail::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : useremail_(arena, from.useremail_),
        _cached_size_{0} {}

UserRetrieveEmail::UserRetrieveEmail(
    ::google::protobuf::Arena* arena,
    const UserRetrieveEmail& from)
    : ::google::protobuf::Message(arena) {
  UserRetrieveEmail* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:email.UserRetrieveEmail)
}
inline PROTOBUF_NDEBUG_INLINE UserRetrieveEmail::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : useremail_(arena),
        _cached_size_{0} {}

inline void UserRetrieveEmail::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserRetrieveEmail::~UserRetrieveEmail() {
  // @@protoc_insertion_point(destructor:email.UserRetrieveEmail)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserRetrieveEmail::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.useremail_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserRetrieveEmail::Clear() {
// @@protoc_insertion_point(message_clear_start:email.UserRetrieveEmail)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.useremail_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserRetrieveEmail::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> UserRetrieveEmail::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserRetrieveEmail_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string useremail = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserRetrieveEmail, _impl_.useremail_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string useremail = 1;
    {PROTOBUF_FIELD_OFFSET(UserRetrieveEmail, _impl_.useremail_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\11\0\0\0\0\0\0"
    "email.UserRetrieveEmail"
    "useremail"
  }},
};

::uint8_t* UserRetrieveEmail::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:email.UserRetrieveEmail)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string useremail = 1;
  if (!this->_internal_useremail().empty()) {
    const std::string& _s = this->_internal_useremail();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "email.UserRetrieveEmail.useremail");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:email.UserRetrieveEmail)
  return target;
}

::size_t UserRetrieveEmail::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:email.UserRetrieveEmail)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string useremail = 1;
  if (!this->_internal_useremail().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_useremail());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserRetrieveEmail::_class_data_ = {
    UserRetrieveEmail::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserRetrieveEmail::GetClassData() const {
  return &_class_data_;
}

void UserRetrieveEmail::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserRetrieveEmail*>(&to_msg);
  auto& from = static_cast<const UserRetrieveEmail&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:email.UserRetrieveEmail)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_useremail().empty()) {
    _this->_internal_set_useremail(from._internal_useremail());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserRetrieveEmail::CopyFrom(const UserRetrieveEmail& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:email.UserRetrieveEmail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserRetrieveEmail::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserRetrieveEmail::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserRetrieveEmail::InternalSwap(UserRetrieveEmail* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.useremail_, &other->_impl_.useremail_, arena);
}

::google::protobuf::Metadata UserRetrieveEmail::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_email_2eproto_getter, &descriptor_table_email_2eproto_once,
      file_level_metadata_email_2eproto[2]);
}
// ===================================================================

class RetrieveEmailReply::_Internal {
 public:
};

RetrieveEmailReply::RetrieveEmailReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:email.RetrieveEmailReply)
}
RetrieveEmailReply::RetrieveEmailReply(
    ::google::protobuf::Arena* arena, const RetrieveEmailReply& from)
    : RetrieveEmailReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RetrieveEmailReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RetrieveEmailReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sendstate_ = {};
}
RetrieveEmailReply::~RetrieveEmailReply() {
  // @@protoc_insertion_point(destructor:email.RetrieveEmailReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RetrieveEmailReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RetrieveEmailReply::Clear() {
// @@protoc_insertion_point(message_clear_start:email.RetrieveEmailReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sendstate_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RetrieveEmailReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RetrieveEmailReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RetrieveEmailReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 sendstate = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RetrieveEmailReply, _impl_.sendstate_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RetrieveEmailReply, _impl_.sendstate_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sendstate = 1;
    {PROTOBUF_FIELD_OFFSET(RetrieveEmailReply, _impl_.sendstate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RetrieveEmailReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:email.RetrieveEmailReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 sendstate = 1;
  if (this->_internal_sendstate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_sendstate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:email.RetrieveEmailReply)
  return target;
}

::size_t RetrieveEmailReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:email.RetrieveEmailReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 sendstate = 1;
  if (this->_internal_sendstate() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_sendstate());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RetrieveEmailReply::_class_data_ = {
    RetrieveEmailReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RetrieveEmailReply::GetClassData() const {
  return &_class_data_;
}

void RetrieveEmailReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RetrieveEmailReply*>(&to_msg);
  auto& from = static_cast<const RetrieveEmailReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:email.RetrieveEmailReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sendstate() != 0) {
    _this->_internal_set_sendstate(from._internal_sendstate());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RetrieveEmailReply::CopyFrom(const RetrieveEmailReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:email.RetrieveEmailReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RetrieveEmailReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RetrieveEmailReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RetrieveEmailReply::InternalSwap(RetrieveEmailReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sendstate_, other->_impl_.sendstate_);
}

::google::protobuf::Metadata RetrieveEmailReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_email_2eproto_getter, &descriptor_table_email_2eproto_once,
      file_level_metadata_email_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace email
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
