// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: email.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_email_2eproto__INCLUDED
#define GRPC_email_2eproto__INCLUDED

#include "email.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace email {

class Email final {
 public:
  static constexpr char const* service_full_name() {
    return "email.Email";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status postRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::email::RegisterEmailReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RegisterEmailReply>> AsyncpostRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RegisterEmailReply>>(AsyncpostRegisterEmailCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RegisterEmailReply>> PrepareAsyncpostRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RegisterEmailReply>>(PrepareAsyncpostRegisterEmailCodeRaw(context, request, cq));
    }
    virtual ::grpc::Status postRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::email::RetrieveEmailReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RetrieveEmailReply>> AsyncpostRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RetrieveEmailReply>>(AsyncpostRetrieveEmailCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RetrieveEmailReply>> PrepareAsyncpostRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::email::RetrieveEmailReply>>(PrepareAsyncpostRetrieveEmailCodeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void postRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail* request, ::email::RegisterEmailReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void postRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail* request, ::email::RegisterEmailReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void postRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail* request, ::email::RetrieveEmailReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void postRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail* request, ::email::RetrieveEmailReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::email::RegisterEmailReply>* AsyncpostRegisterEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::email::RegisterEmailReply>* PrepareAsyncpostRegisterEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::email::RetrieveEmailReply>* AsyncpostRetrieveEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::email::RetrieveEmailReply>* PrepareAsyncpostRetrieveEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status postRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::email::RegisterEmailReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RegisterEmailReply>> AsyncpostRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RegisterEmailReply>>(AsyncpostRegisterEmailCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RegisterEmailReply>> PrepareAsyncpostRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RegisterEmailReply>>(PrepareAsyncpostRegisterEmailCodeRaw(context, request, cq));
    }
    ::grpc::Status postRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::email::RetrieveEmailReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RetrieveEmailReply>> AsyncpostRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RetrieveEmailReply>>(AsyncpostRetrieveEmailCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RetrieveEmailReply>> PrepareAsyncpostRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::email::RetrieveEmailReply>>(PrepareAsyncpostRetrieveEmailCodeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void postRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail* request, ::email::RegisterEmailReply* response, std::function<void(::grpc::Status)>) override;
      void postRegisterEmailCode(::grpc::ClientContext* context, const ::email::UserRegisterEmail* request, ::email::RegisterEmailReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void postRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail* request, ::email::RetrieveEmailReply* response, std::function<void(::grpc::Status)>) override;
      void postRetrieveEmailCode(::grpc::ClientContext* context, const ::email::UserRetrieveEmail* request, ::email::RetrieveEmailReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::email::RegisterEmailReply>* AsyncpostRegisterEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::email::RegisterEmailReply>* PrepareAsyncpostRegisterEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRegisterEmail& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::email::RetrieveEmailReply>* AsyncpostRetrieveEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::email::RetrieveEmailReply>* PrepareAsyncpostRetrieveEmailCodeRaw(::grpc::ClientContext* context, const ::email::UserRetrieveEmail& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_postRegisterEmailCode_;
    const ::grpc::internal::RpcMethod rpcmethod_postRetrieveEmailCode_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* context, const ::email::UserRegisterEmail* request, ::email::RegisterEmailReply* response);
    virtual ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* context, const ::email::UserRetrieveEmail* request, ::email::RetrieveEmailReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_postRegisterEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_postRegisterEmailCode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_postRegisterEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpostRegisterEmailCode(::grpc::ServerContext* context, ::email::UserRegisterEmail* request, ::grpc::ServerAsyncResponseWriter< ::email::RegisterEmailReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_postRetrieveEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_postRetrieveEmailCode() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_postRetrieveEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpostRetrieveEmailCode(::grpc::ServerContext* context, ::email::UserRetrieveEmail* request, ::grpc::ServerAsyncResponseWriter< ::email::RetrieveEmailReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_postRegisterEmailCode<WithAsyncMethod_postRetrieveEmailCode<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_postRegisterEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_postRegisterEmailCode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::email::UserRegisterEmail, ::email::RegisterEmailReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::email::UserRegisterEmail* request, ::email::RegisterEmailReply* response) { return this->postRegisterEmailCode(context, request, response); }));}
    void SetMessageAllocatorFor_postRegisterEmailCode(
        ::grpc::MessageAllocator< ::email::UserRegisterEmail, ::email::RegisterEmailReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::email::UserRegisterEmail, ::email::RegisterEmailReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_postRegisterEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* postRegisterEmailCode(
      ::grpc::CallbackServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_postRetrieveEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_postRetrieveEmailCode() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::email::UserRetrieveEmail, ::email::RetrieveEmailReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::email::UserRetrieveEmail* request, ::email::RetrieveEmailReply* response) { return this->postRetrieveEmailCode(context, request, response); }));}
    void SetMessageAllocatorFor_postRetrieveEmailCode(
        ::grpc::MessageAllocator< ::email::UserRetrieveEmail, ::email::RetrieveEmailReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::email::UserRetrieveEmail, ::email::RetrieveEmailReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_postRetrieveEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* postRetrieveEmailCode(
      ::grpc::CallbackServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_postRegisterEmailCode<WithCallbackMethod_postRetrieveEmailCode<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_postRegisterEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_postRegisterEmailCode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_postRegisterEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_postRetrieveEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_postRetrieveEmailCode() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_postRetrieveEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_postRegisterEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_postRegisterEmailCode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_postRegisterEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpostRegisterEmailCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_postRetrieveEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_postRetrieveEmailCode() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_postRetrieveEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpostRetrieveEmailCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_postRegisterEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_postRegisterEmailCode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->postRegisterEmailCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_postRegisterEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* postRegisterEmailCode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_postRetrieveEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_postRetrieveEmailCode() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->postRetrieveEmailCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_postRetrieveEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* postRetrieveEmailCode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_postRegisterEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_postRegisterEmailCode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::email::UserRegisterEmail, ::email::RegisterEmailReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::email::UserRegisterEmail, ::email::RegisterEmailReply>* streamer) {
                       return this->StreamedpostRegisterEmailCode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_postRegisterEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status postRegisterEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRegisterEmail* /*request*/, ::email::RegisterEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedpostRegisterEmailCode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::email::UserRegisterEmail,::email::RegisterEmailReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_postRetrieveEmailCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_postRetrieveEmailCode() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::email::UserRetrieveEmail, ::email::RetrieveEmailReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::email::UserRetrieveEmail, ::email::RetrieveEmailReply>* streamer) {
                       return this->StreamedpostRetrieveEmailCode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_postRetrieveEmailCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status postRetrieveEmailCode(::grpc::ServerContext* /*context*/, const ::email::UserRetrieveEmail* /*request*/, ::email::RetrieveEmailReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedpostRetrieveEmailCode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::email::UserRetrieveEmail,::email::RetrieveEmailReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_postRegisterEmailCode<WithStreamedUnaryMethod_postRetrieveEmailCode<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_postRegisterEmailCode<WithStreamedUnaryMethod_postRetrieveEmailCode<Service > > StreamedService;
};

}  // namespace email


#endif  // GRPC_email_2eproto__INCLUDED
